name: purchases_flutter
description: A Flutter plugin that makes it simple to add and manage in-app
  purchases (IAP) and subscriptions. Supports Android, iOS, macOS, iPadOS, and
  watchOS.
version: 3.9.0
homepage: https://www.revenuecat.com/
repository: https://github.com/RevenueCat/purchases-flutter
issue_tracker: https://github.com/RevenueCat/purchases-flutter/issues
documentation: https://docs.revenuecat.com/docs

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  json_serializable: ^6.0.0
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      android:
        package: com.revenuecat.purchases_flutter
        pluginClass: PurchasesFlutterPlugin
      ios:
        pluginClass: PurchasesFlutterPlugin
      macos:
        pluginClass: PurchasesFlutterPlugin
